// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $binary from "./routes/binary.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $home from "./routes/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $manifest_json from "./routes/manifest.json.ts";
import * as $projects from "./routes/projects.tsx";
import * as $skills from "./routes/skills.tsx";
import * as $BinaryRain from "./islands/BinaryRain.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $MenuToggle from "./islands/MenuToggle.tsx";
import * as $SkillsMatrix from "./islands/SkillsMatrix.tsx";
import * as $Template from "./islands/Template.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/binary.tsx": $binary,
    "./routes/contact.tsx": $contact,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/manifest.json.ts": $manifest_json,
    "./routes/projects.tsx": $projects,
    "./routes/skills.tsx": $skills,
  },
  islands: {
    "./islands/BinaryRain.tsx": $BinaryRain,
    "./islands/Header.tsx": $Header,
    "./islands/Hero.tsx": $Hero,
    "./islands/MenuToggle.tsx": $MenuToggle,
    "./islands/SkillsMatrix.tsx": $SkillsMatrix,
    "./islands/Template.tsx": $Template,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
